### ISSUE TITLE
锚链接会加空格导致渲染错误

### ISSUE THREAD

**Issue by geekrainy** [hexojs/hexo-filter-auto-spacing#5] opened 2017-04-22 04:22 UTC
参见：
https://github.com/iissnan/hexo-theme-next/issues/1608
https://github.com/hexojs/hexo-renderer-marked/issues/27

**Comment by curbengh** [comment] 2019-08-03 05:38
Duplicate of https://github.com/hexojs/hexo-filter-auto-spacing/issues/4

**Closed as completed by curbengh** 2019-08-03 05:38 UTC
